# Generated by Django 5.2.8 on 2025-12-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SummaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.URLField(blank=True)),
                ('short_preview', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('summarized_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='news.article')),
            ],
        ),
    ]
