# Generated by Django 5.2.8 on 2026-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_topic_article_topics_userarticleinteraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_topics',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='news.topic'),
        ),
        migrations.DeleteModel(
            name='UserArticleInteraction',
        ),
    ]
