# Generated by Django 5.2.8 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_userpreference_preferred_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarypage',
            name='hero_image',
            field=models.URLField(blank=True, default='/static/news/llama-logo.png'),
        ),
    ]
