# Generated by Django 5.2.8 on 2026-01-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_summarypage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticleinteraction',
            name='clicked_at',
        ),
        migrations.RemoveField(
            model_name='userarticleinteraction',
            name='weight',
        ),
    ]
